code_review:
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
pull_request_opened:
  summary: true
  code_review: true
ignore_patterns:
  - "node_modules/**"
  - "build/**"
  - ".gradle/**"
  - "shared-data/**"
  - "dist/**"
  - "**/build/**"
  - "**/node_modules/**"
  - "*.log"
  - "*.txt"
  - "*.mp4"
  - "*.mp3"
  - "*.jpg"
